### ISSUE TITLE
final_suspend promise type compiler transformation

### ISSUE THREAD

**Issue by Ender-events** [dietmarkuehl/co_await-all-the-things#1]
First of all, the co await all the thing conference summarized my understanding of coroutines clearly.

In the slide `C f() { … co_* … }`, the member function `final_suspend` is in try catch block but in https://devblogs.microsoft.com/oldnewthing/20210331-00/?p=105028, the `final_suspend` is outside.
Has anything changed recently?

PS: in the CMakeLists, pgsql is included but is not needed

**Comment by dietmarkuehl** [comment]
Thanks for pointing out the error in the slide: the slides isn't entirely correct, unfortunately. I believe during one of the talks it was also pointed out. That said, I don't think it makes a difference: `final_suspend()` is required to be `noexcept`. Likewise, `await_ready()`, `await_suspend()`, and `await_resume()` also need to be `noexcept`, i.e., I don't think there is a possibility that an exception would escape from any of these functions. As the slides are intended to represent what was presented during the talk, I won't change them.

The requirement for `pgsql` came from original plans to actually do some reasonable asynchronous interaction but it turned out I wouldn't have the time to do that, actually. I have removed the dependency.
